# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpDotenv < Formula
  desc "Convert .env files to 1Password items and vice versa"
  homepage "https://github.com/scriptogre/op-dotenv"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.1.2/op-dotenv_Darwin_x86_64.tar.gz"
      sha256 "9a08f88869f5edee895ddb99002240cac337b498a7ebf4f72b18ffb521b93edb"

      def install
        bin.install "op-dotenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.1.2/op-dotenv_Darwin_arm64.tar.gz"
      sha256 "797b56fcfab4fa9c2ded8a2e92ab333faa2fe572ca2843d5e6554f64b94deb59"

      def install
        bin.install "op-dotenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.1.2/op-dotenv_Linux_x86_64.tar.gz"
      sha256 "9c11ac98b5ee00842b438d0daa53d68430214512cdb469ee07522ef22da57116"
      def install
        bin.install "op-dotenv"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.1.2/op-dotenv_Linux_arm64.tar.gz"
      sha256 "e6d570e51b37f5cc9bd5ee3663afc3af53efcfb1472823119608c1daac4880ae"
      def install
        bin.install "op-dotenv"
      end
    end
  end

  def caveats
    <<~EOS
      Requires 1Password CLI: brew install --cask 1password-cli
    EOS
  end
end
