# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpDotenv < Formula
  desc "Convert .env files to 1Password items and vice versa"
  homepage "https://github.com/scriptogre/op-dotenv"
  version "0.0.6"
  license "MIT"

  depends_on "1password-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.6/op-dotenv_Darwin_x86_64.tar.gz"
      sha256 "5d4ef18d2e65db018c3a04eff9b7bc15374ea3e808797e18e15323b056f6e76d"

      def install
        bin.install "op-dotenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.6/op-dotenv_Darwin_arm64.tar.gz"
      sha256 "751aa4455c9a6560f80d8184d7e7f8c3e0543e068a2a2abab45f84fa2e61d6d2"

      def install
        bin.install "op-dotenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.6/op-dotenv_Linux_x86_64.tar.gz"
      sha256 "71611b6dc2f205c51f75eb179142cf515e62c7fdad27b385308ff98e4ed9b8fd"
      def install
        bin.install "op-dotenv"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.6/op-dotenv_Linux_arm64.tar.gz"
      sha256 "41eb5f6d558c615de602f1505760ddf3c23e2b9173b35dcdbf65c8122a807fea"
      def install
        bin.install "op-dotenv"
      end
    end
  end

  test do
    system "#{bin}/op-dotenv --version"
  end
end
