# This file was generated by GoReleaser. DO NOT EDIT.
cask "op-dotenv" do
  desc "Convert .env files to 1Password items and vice versa"
  homepage "https://github.com/scriptogre/op-dotenv"
  version "0.0.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "op-dotenv"
  depends_on cask: [
      "1password-cli",
    ]

  on_macos do
    on_intel do
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.12/op-dotenv_Darwin_x86_64.tar.gz"
      sha256 "50cccc037215ef1e91504240b8173b513f456baf6139ce2be263eb4f89aa41eb"
    end
    on_arm do
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.12/op-dotenv_Darwin_arm64.tar.gz"
      sha256 "af60a80a4d98d1078b176c57ea9228cc34a9a9388383cbdcea6ad4f8612ba948"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.12/op-dotenv_Linux_x86_64.tar.gz"
      sha256 "ed4b31936b4596559616c4b9beb664d7cbf43aee327c02cb16c0fad32c5e50c4"
    end
    on_arm do
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.12/op-dotenv_Linux_arm64.tar.gz"
      sha256 "53f2f44f92df2631dac9abe72ceb8093f1cef04fa3ae42886035375ebb1c5f9a"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/op-dotenv"]
    end
  end

  caveats do
    "Requires 1Password CLI: brew install --cask 1password-cli"
    ""
    "On first run, macOS may show a security warning. Go to:"
    "System Settings > Privacy & Security > Click "Allow Anyway""
  end

  # No zap stanza required
end
