# This file was generated by GoReleaser. DO NOT EDIT.
cask "op-dotenv" do
  desc "Convert .env files to 1Password items and vice versa"
  homepage "https://github.com/scriptogre/op-dotenv"
  version "0.0.15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "op-dotenv"
  depends_on cask: [
      "1password-cli",
    ]

  on_macos do
    on_intel do
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.15/op-dotenv_Darwin_x86_64.tar.gz"
      sha256 "de7bae17511cb4258de52ff3ff230a9b626517c16a4fe6309e1d7534a2d2be80"
    end
    on_arm do
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.15/op-dotenv_Darwin_arm64.tar.gz"
      sha256 "91bdf4afd1d31b428ae3dd0b3f464f041e13be9ea04c6e1cca4f983d6e2c1930"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.15/op-dotenv_Linux_x86_64.tar.gz"
      sha256 "880cb423158446d6b8e93cc776dcb97569b8079d0f797eee241dea45ccaf0df8"
    end
    on_arm do
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.15/op-dotenv_Linux_arm64.tar.gz"
      sha256 "4b29ce82de7faa742dc56db8b4eb70b06a0f8eecb0c3990a87acc8845b640e6f"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/op-dotenv"]
    end
  end

  caveats do
    "Requires 1Password CLI: brew install --cask 1password-cli"
    ""
    "On first run, macOS may show a security warning. Go to:"
    "System Settings > Privacy & Security > Click 'Allow Anyway'"
  end

  # No zap stanza required
end
