# This file was generated by GoReleaser. DO NOT EDIT.
cask "op-dotenv" do
  desc "Convert .env files to 1Password items and vice versa"
  homepage "https://github.com/scriptogre/op-dotenv"
  version "0.0.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "op-dotenv"
  depends_on cask: [
      "1password-cli",
    ]

  on_macos do
    on_intel do
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.17/op-dotenv_Darwin_x86_64.tar.gz"
      sha256 "58734e67bdc6dff593209de5ee1b2aaa4abb885574de3aab72a92ae25aafc2be"
    end
    on_arm do
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.17/op-dotenv_Darwin_arm64.tar.gz"
      sha256 "096dd43c08eced4386d34f6bfb07b84c611b9496ed5084532965418693b1fda1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.17/op-dotenv_Linux_x86_64.tar.gz"
      sha256 "1143948845da1835b0c934728ca112bdb1a4fb48fa520b5ebbc0e22d8cd7700b"
    end
    on_arm do
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.17/op-dotenv_Linux_arm64.tar.gz"
      sha256 "315a9bccf2474bd4d3c5ecab3c7829a84a3f635630594b1f0a70d5e0c3b2b20e"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/op-dotenv"]
    end
  end

  caveats do
    "Requires 1Password CLI: brew install --cask 1password-cli"
    ""
    "On first run, macOS may show a security warning. Go to:"
    "System Settings > Privacy & Security > Click 'Allow Anyway'"
  end

  # No zap stanza required
end
