# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpDotenv < Formula
  desc "Convert .env files to 1Password items and vice versa"
  homepage "https://github.com/scriptogre/op-dotenv"
  version "0.0.8"
  license "MIT"

  depends_on "1password-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.8/op-dotenv_Darwin_x86_64.tar.gz"
      sha256 "067eb3eff3af3b49fe4233f8fbb3f4f69f7ee26f9003e6abfe3e7ef5ce2d6d04"

      def install
        bin.install "op-dotenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.8/op-dotenv_Darwin_arm64.tar.gz"
      sha256 "fa59541d0105354ff2521000e792e867b831584b73e166d6bf05151208a014f2"

      def install
        bin.install "op-dotenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.8/op-dotenv_Linux_x86_64.tar.gz"
      sha256 "3fbb2c65faa82b9c3ca1eb4c10332c7158a693a0b52c9dd0235743e07d1c7f3d"
      def install
        bin.install "op-dotenv"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/scriptogre/op-dotenv/releases/download/v0.0.8/op-dotenv_Linux_arm64.tar.gz"
      sha256 "94868d4d75ec188f688209fe5f05cca9f29464940b60b058f73a6bcbf12f011f"
      def install
        bin.install "op-dotenv"
      end
    end
  end

  test do
    system "#{bin}/op-dotenv --version"
  end
end
